app:
  name: ui
  image:
    repository: 'onecx/onecx-shell-ui'
  routing:
    enabled: true
    path: /newShell/

  operator:
    # Keycloak
    keycloak:
      client:
        enabled: true
        spec:
          kcConfig:
            clientId: 'onecx-shell-ui'
    slot:
      enabled: true
      specs:
        onecx-shell-vertical-menu:
          name: 'onecx-shell-vertical-menu'
          description: 'Shell vertical menu'
        onecx-shell-horizontal-menu:
          name: 'onecx-shell-horizontal-menu'
          description: 'Shell horizontal menu'
        onecx-shell-header-right:
          name: 'onecx-shell-header-right'
          description: 'Shell header right'
        onecx-shell-sub-header:
          name: 'onecx-shell-sub-header'
          description: 'Shell sub header menu'
        onecx-shell-footer:
          name: 'onecx-shell-footer'
          description: 'Shell footer'
        onecx-search-config:
          name: 'onecx-search-config'
          description: 'Shell search config'
        onecx-column-group-selection:
          name: 'onecx-column-group-selection'
          description: 'Shell column group selection'
# PIPE Config
